# Generated by Django 4.0.3 on 2022-03-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('physics', models.CharField(max_length=100)),
                ('chemistry', models.CharField(max_length=100)),
                ('Maths', models.CharField(max_length=100)),
                ('Botany', models.CharField(max_length=100)),
                ('Zoology', models.CharField(max_length=100)),
                ('English', models.CharField(max_length=100)),
                ('Total', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
