# Generated by Django 4.0.3 on 2022-03-09 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrudserializer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
