# Generated by Django 4.0.3 on 2022-03-09 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(upload_to='profile')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths_mrk', models.CharField(default=0, max_length=100)),
                ('physics_mrk', models.CharField(default=0, max_length=100)),
                ('chemistry_mrk', models.CharField(default=0, max_length=100)),
                ('english_mrk', models.CharField(default=0, max_length=100)),
                ('botany_mrk', models.CharField(default=0, max_length=100)),
                ('zoology_mrk', models.CharField(default=0, max_length=100)),
                ('semester', models.CharField(default=0, max_length=100)),
                ('total', models.CharField(default=0, max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentwithrelation.student')),
            ],
        ),
    ]
