# Generated by Django 4.0.3 on 2022-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentwithrelation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_class', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='studentwithrelation.student')),
            ],
        ),
    ]
